[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://marquebackend-production.up.railway.app/api/v1"
NEXT_PUBLIC_APP_URL = "https://marque.website"
